# This workflow ensures that all PRs are correctly labeled

name: ForkChecker
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        cd .github/forkChecker
        npm install
        node index.js
